# AUTOGENERATED FROM 'bot/happy_school_bot/db_queries/check_child.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class CheckChildResult(NoPydanticValidation):
    id: uuid.UUID


async def check_child(
    executor: edgedb.AsyncIOExecutor,
    *,
    qrcode_id: uuid.UUID,
    action: str,
    checked_by: uuid.UUID,
) -> CheckChildResult:
    return await executor.query_single(
        """\
        insert ChildEntranceCheck {
            qrcode := (
                select EntranceQRcode filter .id =<uuid>$qrcode_id
            ),
            action := <str>$action,
            checked_by := (
                select User filter .id =<uuid>$checked_by
            )

        }\
        """,
        qrcode_id=qrcode_id,
        action=action,
        checked_by=checked_by,
    )
