# AUTOGENERATED FROM 'bot/happy_school_bot/db_queries/find_active_qr_code_by_parent_user_id.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class FindActiveQrCodeByParentUserIdResult(NoPydanticValidation):
    id: uuid.UUID
    students: list[FindActiveQrCodeByParentUserIdResultStudentsItem]


@dataclasses.dataclass
class FindActiveQrCodeByParentUserIdResultStudentsItem(NoPydanticValidation):
    id: uuid.UUID
    user: FindActiveQrCodeByParentUserIdResultStudentsItemUser


@dataclasses.dataclass
class FindActiveQrCodeByParentUserIdResultStudentsItemUser(NoPydanticValidation):
    id: uuid.UUID
    first_name: str
    last_name: str


async def find_active_qr_code_by_parent_user_id(
    executor: edgedb.AsyncIOExecutor,
    *,
    parent_user_id: uuid.UUID,
) -> list[FindActiveQrCodeByParentUserIdResult]:
    return await executor.query(
        """\
        select EntranceQRcode {
            students: {
                user: {
                    first_name,
                    last_name
                }
            }
        }
        filter .parent.user.id = <uuid>$parent_user_id and
        .is_deleted = false\
        """,
        parent_user_id=parent_user_id,
    )
