# AUTOGENERATED FROM 'bot/happy_school_bot/db_queries/find_qr_code_by_parent_user_id.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass

        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class FindQrCodeByParentUserIdResult(NoPydanticValidation):
    id: uuid.UUID
    students: list[FindQrCodeByParentUserIdResultStudentsItem]


@dataclasses.dataclass
class FindQrCodeByParentUserIdResultStudentsItem(NoPydanticValidation):
    id: uuid.UUID
    user: FindQrCodeByParentUserIdResultStudentsItemUser


@dataclasses.dataclass
class FindQrCodeByParentUserIdResultStudentsItemUser(NoPydanticValidation):
    id: uuid.UUID
    first_name: str
    last_name: str


async def find_qr_code_by_parent_user_id(
    executor: edgedb.AsyncIOExecutor,
    *,
    parent_user_id: uuid.UUID,
) -> list[FindQrCodeByParentUserIdResult]:
    return await executor.query(
        """\
        select EntranceQRcode {
            students: {
                user: {
                    first_name,
                    last_name
                }
            }
        }
        filter .parent.user.id = <uuid>$parent_user_id\
        """,
        parent_user_id=parent_user_id,
    )
