# AUTOGENERATED FROM 'bot/happy_school_bot/db_queries/get_children_by_parent_user_id.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import datetime
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class GetChildrenByParentUserIdResult(NoPydanticValidation):
    id: uuid.UUID
    updated_at: datetime.datetime
    created_at: datetime.datetime
    user: GetChildrenByParentUserIdResultUser


@dataclasses.dataclass
class GetChildrenByParentUserIdResultUser(NoPydanticValidation):
    id: uuid.UUID
    first_name: str
    last_name: str
    status: str


async def get_children_by_parent_user_id(
    executor: edgedb.AsyncIOExecutor,
    *,
    parent_user_id: uuid.UUID,
) -> list[GetChildrenByParentUserIdResult]:
    return await executor.query(
        """\
        select Student {
            id,
            updated_at,
            created_at,
            user: {
                id,
                first_name,
                last_name,
                status
            }
        }
        filter .parents.user.id = <uuid>$parent_user_id\
        """,
        parent_user_id=parent_user_id,
    )
