# AUTOGENERATED FROM 'bot/happy_school_bot/db_queries/get_user_by_tg_id.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class GetUserByTgIdResult(NoPydanticValidation):
    first_name: str
    last_name: str
    status: str
    id: uuid.UUID
    is_teacher: bool
    is_student: bool
    is_admin: bool
    is_parent: bool
    tg_id: int | None


async def get_user_by_tg_id(
    executor: edgedb.AsyncIOExecutor,
    *,
    tg_id: int,
) -> GetUserByTgIdResult | None:
    return await executor.query_single(
        """\
        select User {first_name, last_name, status, id, is_teacher, is_student, is_admin, is_parent, tg_id}
        filter User.tg_id = <int64>$tg_id\
        """,
        tg_id=tg_id,
    )
