# AUTOGENERATED FROM 'app/dependencies/db_queries/get_email_from_current_identity.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class GetEmailFromCurrentIdentityResult(NoPydanticValidation):
    id: uuid.UUID
    email: str


async def get_email_from_current_identity(
    executor: edgedb.AsyncIOExecutor,
) -> GetEmailFromCurrentIdentityResult | None:
    return await executor.query_single(
        """\
        select ext::auth::EmailFactor {
          email,
        } filter .identity = global ext::auth::ClientTokenIdentity\
        """,
    )
