# AUTOGENERATED FROM 'app/dependencies/db_queries/select_current_user.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class SelectCurrentUserResult(NoPydanticValidation):
    first_name: str
    last_name: str
    status: str
    id: uuid.UUID
    is_teacher: bool
    is_student: bool
    is_admin: bool
    is_parent: bool


async def select_current_user(
    executor: edgedb.AsyncIOExecutor,
) -> SelectCurrentUserResult | None:
    return await executor.query_single(
        """\
        select User 
            {
                 first_name,
                 last_name,
                 status,
                 id,
                 is_teacher,
                 is_student,
                 is_admin,
                 is_parent,
             }
        filter User.id = global current_user.id
        limit 1\
        """,
    )
