# AUTOGENERATED FROM 'reset_db.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations

import dataclasses
import uuid

import edgedb


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = list
        return []


@dataclasses.dataclass
class ResetDbResult(NoPydanticValidation):
    id: uuid.UUID


async def reset_db(
    executor: edgedb.AsyncIOExecutor,
) -> list[ResetDbResult]:
    return await executor.query(
        """\
        delete Class;
        delete Homework;
        delete Subject;
        delete User;
        delete ext::auth::Factor;
        delete ext::auth::Identity;
        delete ext::auth::LocalIdentity;\
        """,
    )
